##  Java 异常类层次结构图
![Java异常类层次结构图](https://note.youdao.com/yws/public/resource/443915cbe32b82c13708e64cb87b94c1/xmlnote/162299FE2B6A486C93E087238CA921FF/12484)
- 在 Java 中，所有的异常都有一个共同的祖先 java.lang 包中的 `Throwable 类`
- Throwable： 有两个重要的子类：`Exception（异常）` 和 `Error（错误）` ，二者都是 Java 异常处理的重要子类，各自都包含大量子类
- 注意：异常和错误的区别：`异常能被程序本身处理，错误是无法处理`

## Error
- Error是指在正常情况下不太可能出现的错误，它`与代码的编写`无关，通常是表示运行时JVM出现的问题，比如系统内部错误、或者资源不足等，这些异常发生时，Java 虚拟机（JVM）一般会选择`线程终止`
- 常见的有： OutOfMemoryError（ 内存溢出 ） 、 VirtualMachineError（虚拟机错误）、 NoClassDefFoundError（类定义错误）

## Exception
### 可检查异常 （Exception）
- 需要我们在程序中`必须`进行显式的捕获处理，否则将会`编译报错`
- 常见的有IOException、SQLException

### 不可检查异常 （ RuntimeException ）
- 程序本身`不要求`我们强制去捕获处理，但是可以`避免`代码在运行过程中的逻辑错误
- 常见的有NullPointerException（空指针）、ArrayIndexOutOfBoundException（下标越界异常）

## 异常处理注意事项
### 谨慎使用异常处理
- try..catch会造成程序的`额外开销`，所以建议只捕获关键的代码，切忌`不要用try包住一个很大的代码块`
- Java每实例化一个Exception，就会`对当时的栈进行快照`，如果操作比较频繁，那么对资源的开销就不能被忽略

### finally和try中的return哪个先执行
- 当在 try 块或 catch 块中遇到 return语句时，finally 语句块将在`方法返回之前被执行`

### 如果在finally里面对将要return的变量做了修改，返回的是修改后的值吗
- try中有return，会先将值`暂存`，无论finally语句中对该值做什么处理，`最终返回的都是try语句中的暂存值`

### finally和try的return
- 如果try，finally语句里均有return，`忽略try的return，而使用finally的return`
- `建议finally不要带return`

### finally 块不会被执行的情况
1. 在 finally 语句块第一行发生了异常。 因为在其他行，finally 块还是会得到执行
2. 在前面的代码中用了 System.exit(int)已退出程序。 exit 是带参函数 ；若该语句在异常语句之后，finally 会执行
3. 程序所在的线程死亡
4. 关闭 CPU